version: '3.4'

services:
  pakodemyproject:
    image: ${DOCKER_REGISTRY-}pakodemyproject
    build:
      context: .
      dockerfile: PakodemyProject\Dockerfile

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
          - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1


  redis_image:
        image: redis
        container_name: cache
        ports:
            - "6379:6379"  
